import Head from "next/head";
import { HeroSection } from "@/components/home/HeroSection";
import { AboutSection } from "@/components/about/AboutSection";
import { JobStagesSection } from "@/components/home/JobStagesSection";
import { FeaturesSection } from "@/components/home/FeaturesSection";
import { CourseCategories } from "@/components/home/CourseCategories";
import { Testimonials } from "@/components/home/Testimonials";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
// import { UpcomingEventSection } from "@/components/about/UpcomingEventSection";
import { WorkshopSection } from "@/components/about/WorkshopSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Vision Wisdom Recruitment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vss.png" />
      </Head>

      <Navbar />

      <HeroSection />
      <AboutSection />
      <WorkshopSection/>
      {/* <JobStagesSection /> */}
      {/* <CourseCategories /> */}
      {/* <UpcomingEventSection/> */}
    
      <Testimonials />

      <Footer />
    </>
  );
}
